OPT= -O0 
DEBUG= -g 
CMP=g++  $(DEBUG) $(OPT) 
GCC=gcc  $(DEBUG) $(OPT) 

all: codelite_indexer
codelite_indexer_objects = \
	Debug/cl_indexer_reply.o\
	Debug/cl_indexer_request.o\
	Debug/clindexerprotocol.o\
	Debug/named_pipe.o\
	Debug/named_pipe_client.o\
	Debug/named_pipe_server.o\
	Debug/np_connections_server.o\
	Debug/args.o\
	Debug/asm.o\
	Debug/asp.o\
	Debug/awk.o\
	Debug/beta.o\
	Debug/c.o\
	Debug/clist.o\
	Debug/cobol.o\
	Debug/debug.o\
	Debug/eiffel.o\
	Debug/entry.o\
	Debug/erlang.o\
	Debug/fortran.o\
	Debug/get.o\
	Debug/html.o\
	Debug/jscript.o\
	Debug/keyword.o\
	Debug/lisp.o\
	Debug/lregex.o\
	Debug/lua.o\
	Debug/main.o\
	Debug/make.o\
	Debug/options.o\
	Debug/parse.o\
	Debug/pascal.o\
	Debug/perl.o\
	Debug/php.o\
	Debug/python.o\
	Debug/read.o\
	Debug/readtags.o\
	Debug/rexx.o\
	Debug/routines.o\
	Debug/ruby.o\
	Debug/scheme.o\
	Debug/sh.o\
	Debug/slang.o\
	Debug/sml.o\
	Debug/sort.o\
	Debug/sql.o\
	Debug/string_util.o\
	Debug/strlist.o\
	Debug/tcl.o\
	Debug/verilog.o\
	Debug/vim.o\
	Debug/vstring.o\
	Debug/yacc.o\
	Debug/codelite_index_main.o\
	Debug/ethread_unix.o\
	Debug/ethread_win.o\
	Debug/utils.o\
	Debug/workerthread.o\

Debug/cl_indexer_reply.o: network/cl_indexer_reply.cpp Debug/cl_indexer_reply.o.d
	$(CMP)  -c network/cl_indexer_reply.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/cl_indexer_reply.o
Debug/cl_indexer_reply.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/cl_indexer_reply.o -MFDebug/cl_indexer_reply.o.d  -MM network/cl_indexer_reply.cpp
Debug/cl_indexer_request.o: network/cl_indexer_request.cpp Debug/cl_indexer_request.o.d
	$(CMP)  -c network/cl_indexer_request.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/cl_indexer_request.o
Debug/cl_indexer_request.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/cl_indexer_request.o -MFDebug/cl_indexer_request.o.d  -MM network/cl_indexer_request.cpp
Debug/clindexerprotocol.o: network/clindexerprotocol.cpp Debug/clindexerprotocol.o.d
	$(CMP)  -c network/clindexerprotocol.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/clindexerprotocol.o
Debug/clindexerprotocol.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/clindexerprotocol.o -MFDebug/clindexerprotocol.o.d  -MM network/clindexerprotocol.cpp
Debug/named_pipe.o: network/named_pipe.cpp Debug/named_pipe.o.d
	$(CMP)  -c network/named_pipe.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/named_pipe.o
Debug/named_pipe.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/named_pipe.o -MFDebug/named_pipe.o.d  -MM network/named_pipe.cpp
Debug/named_pipe_client.o: network/named_pipe_client.cpp Debug/named_pipe_client.o.d
	$(CMP)  -c network/named_pipe_client.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/named_pipe_client.o
Debug/named_pipe_client.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/named_pipe_client.o -MFDebug/named_pipe_client.o.d  -MM network/named_pipe_client.cpp
Debug/named_pipe_server.o: network/named_pipe_server.cpp Debug/named_pipe_server.o.d
	$(CMP)  -c network/named_pipe_server.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/named_pipe_server.o
Debug/named_pipe_server.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/named_pipe_server.o -MFDebug/named_pipe_server.o.d  -MM network/named_pipe_server.cpp
Debug/np_connections_server.o: network/np_connections_server.cpp Debug/np_connections_server.o.d
	$(CMP)  -c network/np_connections_server.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/np_connections_server.o
Debug/np_connections_server.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/np_connections_server.o -MFDebug/np_connections_server.o.d  -MM network/np_connections_server.cpp
Debug/args.o: libctags/args.c Debug/args.o.d
	$(GCC) -c libctags/args.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/args.o
Debug/args.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/args.o -MFDebug/args.o.d  -MM libctags/args.c
Debug/asm.o: libctags/asm.c Debug/asm.o.d
	$(GCC) -c libctags/asm.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/asm.o
Debug/asm.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/asm.o -MFDebug/asm.o.d  -MM libctags/asm.c
Debug/asp.o: libctags/asp.c Debug/asp.o.d
	$(GCC) -c libctags/asp.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/asp.o
Debug/asp.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/asp.o -MFDebug/asp.o.d  -MM libctags/asp.c
Debug/awk.o: libctags/awk.c Debug/awk.o.d
	$(GCC) -c libctags/awk.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/awk.o
Debug/awk.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/awk.o -MFDebug/awk.o.d  -MM libctags/awk.c
Debug/beta.o: libctags/beta.c Debug/beta.o.d
	$(GCC) -c libctags/beta.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/beta.o
Debug/beta.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/beta.o -MFDebug/beta.o.d  -MM libctags/beta.c
Debug/c.o: libctags/c.c Debug/c.o.d
	$(GCC) -c libctags/c.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/c.o
Debug/c.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/c.o -MFDebug/c.o.d  -MM libctags/c.c
Debug/clist.o: libctags/clist.c Debug/clist.o.d
	$(GCC) -c libctags/clist.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/clist.o
Debug/clist.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/clist.o -MFDebug/clist.o.d  -MM libctags/clist.c
Debug/cobol.o: libctags/cobol.c Debug/cobol.o.d
	$(GCC) -c libctags/cobol.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/cobol.o
Debug/cobol.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/cobol.o -MFDebug/cobol.o.d  -MM libctags/cobol.c
Debug/debug.o: libctags/debug.c Debug/debug.o.d
	$(GCC) -c libctags/debug.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/debug.o
Debug/debug.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/debug.o -MFDebug/debug.o.d  -MM libctags/debug.c
Debug/eiffel.o: libctags/eiffel.c Debug/eiffel.o.d
	$(GCC) -c libctags/eiffel.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/eiffel.o
Debug/eiffel.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/eiffel.o -MFDebug/eiffel.o.d  -MM libctags/eiffel.c
Debug/entry.o: libctags/entry.c Debug/entry.o.d
	$(GCC) -c libctags/entry.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/entry.o
Debug/entry.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/entry.o -MFDebug/entry.o.d  -MM libctags/entry.c
Debug/erlang.o: libctags/erlang.c Debug/erlang.o.d
	$(GCC) -c libctags/erlang.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/erlang.o
Debug/erlang.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/erlang.o -MFDebug/erlang.o.d  -MM libctags/erlang.c
Debug/fortran.o: libctags/fortran.c Debug/fortran.o.d
	$(GCC) -c libctags/fortran.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/fortran.o
Debug/fortran.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/fortran.o -MFDebug/fortran.o.d  -MM libctags/fortran.c
Debug/get.o: libctags/get.c Debug/get.o.d
	$(GCC) -c libctags/get.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/get.o
Debug/get.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/get.o -MFDebug/get.o.d  -MM libctags/get.c
Debug/html.o: libctags/html.c Debug/html.o.d
	$(GCC) -c libctags/html.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/html.o
Debug/html.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/html.o -MFDebug/html.o.d  -MM libctags/html.c
Debug/jscript.o: libctags/jscript.c Debug/jscript.o.d
	$(GCC) -c libctags/jscript.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/jscript.o
Debug/jscript.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/jscript.o -MFDebug/jscript.o.d  -MM libctags/jscript.c
Debug/keyword.o: libctags/keyword.c Debug/keyword.o.d
	$(GCC) -c libctags/keyword.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/keyword.o
Debug/keyword.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/keyword.o -MFDebug/keyword.o.d  -MM libctags/keyword.c
Debug/lisp.o: libctags/lisp.c Debug/lisp.o.d
	$(GCC) -c libctags/lisp.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/lisp.o
Debug/lisp.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/lisp.o -MFDebug/lisp.o.d  -MM libctags/lisp.c
Debug/lregex.o: libctags/lregex.c Debug/lregex.o.d
	$(GCC) -c libctags/lregex.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/lregex.o
Debug/lregex.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/lregex.o -MFDebug/lregex.o.d  -MM libctags/lregex.c
Debug/lua.o: libctags/lua.c Debug/lua.o.d
	$(GCC) -c libctags/lua.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/lua.o
Debug/lua.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/lua.o -MFDebug/lua.o.d  -MM libctags/lua.c
Debug/main.o: libctags/main.c Debug/main.o.d
	$(GCC) -c libctags/main.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/main.o
Debug/main.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/main.o -MFDebug/main.o.d  -MM libctags/main.c
Debug/make.o: libctags/make.c Debug/make.o.d
	$(GCC) -c libctags/make.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/make.o
Debug/make.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/make.o -MFDebug/make.o.d  -MM libctags/make.c
Debug/options.o: libctags/options.c Debug/options.o.d
	$(GCC) -c libctags/options.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/options.o
Debug/options.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/options.o -MFDebug/options.o.d  -MM libctags/options.c
Debug/parse.o: libctags/parse.c Debug/parse.o.d
	$(GCC) -c libctags/parse.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/parse.o
Debug/parse.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/parse.o -MFDebug/parse.o.d  -MM libctags/parse.c
Debug/pascal.o: libctags/pascal.c Debug/pascal.o.d
	$(GCC) -c libctags/pascal.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/pascal.o
Debug/pascal.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/pascal.o -MFDebug/pascal.o.d  -MM libctags/pascal.c
Debug/perl.o: libctags/perl.c Debug/perl.o.d
	$(GCC) -c libctags/perl.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/perl.o
Debug/perl.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/perl.o -MFDebug/perl.o.d  -MM libctags/perl.c
Debug/php.o: libctags/php.c Debug/php.o.d
	$(GCC) -c libctags/php.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/php.o
Debug/php.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/php.o -MFDebug/php.o.d  -MM libctags/php.c
Debug/python.o: libctags/python.c Debug/python.o.d
	$(GCC) -c libctags/python.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/python.o
Debug/python.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/python.o -MFDebug/python.o.d  -MM libctags/python.c
Debug/read.o: libctags/read.c Debug/read.o.d
	$(GCC) -c libctags/read.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/read.o
Debug/read.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/read.o -MFDebug/read.o.d  -MM libctags/read.c
Debug/readtags.o: libctags/readtags.c Debug/readtags.o.d
	$(GCC) -c libctags/readtags.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/readtags.o
Debug/readtags.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/readtags.o -MFDebug/readtags.o.d  -MM libctags/readtags.c
Debug/rexx.o: libctags/rexx.c Debug/rexx.o.d
	$(GCC) -c libctags/rexx.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/rexx.o
Debug/rexx.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/rexx.o -MFDebug/rexx.o.d  -MM libctags/rexx.c
Debug/routines.o: libctags/routines.c Debug/routines.o.d
	$(GCC) -c libctags/routines.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/routines.o
Debug/routines.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/routines.o -MFDebug/routines.o.d  -MM libctags/routines.c
Debug/ruby.o: libctags/ruby.c Debug/ruby.o.d
	$(GCC) -c libctags/ruby.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/ruby.o
Debug/ruby.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/ruby.o -MFDebug/ruby.o.d  -MM libctags/ruby.c
Debug/scheme.o: libctags/scheme.c Debug/scheme.o.d
	$(GCC) -c libctags/scheme.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/scheme.o
Debug/scheme.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/scheme.o -MFDebug/scheme.o.d  -MM libctags/scheme.c
Debug/sh.o: libctags/sh.c Debug/sh.o.d
	$(GCC) -c libctags/sh.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/sh.o
Debug/sh.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/sh.o -MFDebug/sh.o.d  -MM libctags/sh.c
Debug/slang.o: libctags/slang.c Debug/slang.o.d
	$(GCC) -c libctags/slang.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/slang.o
Debug/slang.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/slang.o -MFDebug/slang.o.d  -MM libctags/slang.c
Debug/sml.o: libctags/sml.c Debug/sml.o.d
	$(GCC) -c libctags/sml.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/sml.o
Debug/sml.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/sml.o -MFDebug/sml.o.d  -MM libctags/sml.c
Debug/sort.o: libctags/sort.c Debug/sort.o.d
	$(GCC) -c libctags/sort.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/sort.o
Debug/sort.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/sort.o -MFDebug/sort.o.d  -MM libctags/sort.c
Debug/sql.o: libctags/sql.c Debug/sql.o.d
	$(GCC) -c libctags/sql.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/sql.o
Debug/sql.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/sql.o -MFDebug/sql.o.d  -MM libctags/sql.c
Debug/string_util.o: libctags/string_util.c Debug/string_util.o.d
	$(GCC) -c libctags/string_util.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/string_util.o
Debug/string_util.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/string_util.o -MFDebug/string_util.o.d  -MM libctags/string_util.c
Debug/strlist.o: libctags/strlist.c Debug/strlist.o.d
	$(GCC) -c libctags/strlist.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/strlist.o
Debug/strlist.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/strlist.o -MFDebug/strlist.o.d  -MM libctags/strlist.c
Debug/tcl.o: libctags/tcl.c Debug/tcl.o.d
	$(GCC) -c libctags/tcl.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/tcl.o
Debug/tcl.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/tcl.o -MFDebug/tcl.o.d  -MM libctags/tcl.c
Debug/verilog.o: libctags/verilog.c Debug/verilog.o.d
	$(GCC) -c libctags/verilog.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/verilog.o
Debug/verilog.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/verilog.o -MFDebug/verilog.o.d  -MM libctags/verilog.c
Debug/vim.o: libctags/vim.c Debug/vim.o.d
	$(GCC) -c libctags/vim.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/vim.o
Debug/vim.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/vim.o -MFDebug/vim.o.d  -MM libctags/vim.c
Debug/vstring.o: libctags/vstring.c Debug/vstring.o.d
	$(GCC) -c libctags/vstring.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/vstring.o
Debug/vstring.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/vstring.o -MFDebug/vstring.o.d  -MM libctags/vstring.c
Debug/yacc.o: libctags/yacc.c Debug/yacc.o.d
	$(GCC) -c libctags/yacc.c -DHAVE_CONFIG_H -I. -Ilibctags  -o Debug/yacc.o
Debug/yacc.o.d:
	$(GCC) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/yacc.o -MFDebug/yacc.o.d  -MM libctags/yacc.c
Debug/codelite_index_main.o: codelite_index_main.cpp Debug/codelite_index_main.o.d
	$(CMP)  -c codelite_index_main.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/codelite_index_main.o
Debug/codelite_index_main.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/codelite_index_main.o -MFDebug/codelite_index_main.o.d  -MM codelite_index_main.cpp
Debug/ethread_unix.o: ethread_unix.cpp Debug/ethread_unix.o.d
	$(CMP)  -c ethread_unix.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/ethread_unix.o
Debug/ethread_unix.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/ethread_unix.o -MFDebug/ethread_unix.o.d  -MM ethread_unix.cpp
Debug/ethread_win.o: ethread_win.cpp Debug/ethread_win.o.d
	$(CMP)  -c ethread_win.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/ethread_win.o
Debug/ethread_win.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/ethread_win.o -MFDebug/ethread_win.o.d  -MM ethread_win.cpp
Debug/utils.o: utils.cpp Debug/utils.o.d
	$(CMP)  -c utils.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/utils.o
Debug/utils.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/utils.o -MFDebug/utils.o.d  -MM utils.cpp
Debug/workerthread.o: workerthread.cpp Debug/workerthread.o.d
	$(CMP)  -c workerthread.cpp -DHAVE_CONFIG_H -I. -Ilibctags -o Debug/workerthread.o
Debug/workerthread.o.d:
	$(CMP) -DHAVE_CONFIG_H -I. -Ilibctags  -MTDebug/workerthread.o -MFDebug/workerthread.o.d  -MM workerthread.cpp
-include Debug/*.d

codelite_indexer: make_dirs $(codelite_indexer_objects)
	$(CMP) -o codelite_indexer $(codelite_indexer_objects) -lpthread -ldl 

make_dirs:
	@echo
	@echo "----------Building project:[ codelite_indexer - Debug ]----------"
	@echo
	test -d Debug || mkdir Debug

clean: 
	$(RM) -fr Debug/*.o
	$(RM) -fr Debug/*.o.d
	$(RM) -fr codelite_indexer
