/**
  \file 

  \brief EmbeddedLite file
  \author V. Ridtchenko

  \notes

  Copyright: (C) 2010 by Victor Ridtchenko

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
*/
#ifndef __macrosdlg__
#define __macrosdlg__

/**
@file
Subclass of MacrosBaseDlg, which is generated by wxFormBuilder.
*/

#include "macrosbasedlg.h"

/** Implementing MacrosBaseDlg */
class MacrosDlg : public MacrosBaseDlg
{
	long m_item;
	int m_content;
	
public:	
	enum {
		MacrosProject,
		MacrosCompiler,
		MacrosExternalTools
	};
	
protected:
	// Handlers for MacrosBaseDlg events.
	void OnItemRightClick( wxListEvent& event );
	void OnCopy(wxCommandEvent &e);
	void Initialize();
	void AddMacro(const wxString &name, const wxString &desc);
	
	DECLARE_EVENT_TABLE()
	
public:
	/** Constructor */
	MacrosDlg( wxWindow* parent, int content );
	virtual ~MacrosDlg();
};

#endif // __macrosdlg__
