/**
  \file 

  \brief EmbeddedLite file
  \author V. Ridtchenko

  \notes

  Copyright: (C) 2010 by Victor Ridtchenko

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
*/
#ifndef __nameanddescdlg__
#define __nameanddescdlg__

/**
@file
Subclass of NameAndDescBaseDlg, which is generated by wxFormBuilder.
*/

#include "nameanddescbasedlg.h"
class IManager;

/** Implementing NameAndDescBaseDlg */
class NameAndDescDlg : public NameAndDescBaseDlg
{
protected:
	// Handlers for NameAndDescBaseDlg events.
	void OnButtonOK( wxCommandEvent& event );
	void OnButtonCancel( wxCommandEvent& event );

public:
	/** Constructor */
	NameAndDescDlg( wxWindow* parent, IManager *manager, const wxString &name );
	wxString GetName() const {return m_textCtrlName->GetValue();}
	wxString GetDescription() const {return m_textCtrlDescription->GetValue();}
	wxString GetType() const {return m_choiceType->GetValue();}
};

#endif // __nameanddescdlg__

