/**
  \file 

  \brief EmbeddedLite file
  \author V. Ridtchenko

  \notes

  Copyright: (C) 2010 by Victor Ridtchenko

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
*/
#ifndef __threebuttondlg__
#define __threebuttondlg__

/**
@file
Subclass of ThreeButtonBaseDlg, which is generated by wxFormBuilder.
*/

#include "threebuttonbasedlg.h"

/** Implementing ThreeButtonBaseDlg */
class ThreeButtonDlg : public ThreeButtonBaseDlg
{
	
protected:
	void OnButtonYes(wxCommandEvent &e);
	void OnButtonNo(wxCommandEvent &e);
	void OnButtonCancel(wxCommandEvent &e);
	
public:
	/** Constructor */
	ThreeButtonDlg( wxWindow* parent, const wxString &msg, const wxString &caption );
	bool GetDontAskMeAgain() const {return m_checkBoxRememberMyAnwer->GetValue();}
};

#endif // __threebuttondlg__
