/**
  \file 

  \brief EmbeddedLite file
  \author V. Ridtchenko

  \notes

  Copyright: (C) 2010 by Victor Ridtchenko

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
*/
#ifndef _ABOUTDLG_H_
#define _ABOUTDLG_H_

/**
@file
Subclass of AboutDlgBase, which is generated by wxFormBuilder.
*/

#include "aboutdlgbase.h"
#include <wx/bitmap.h>

/** Implementing AboutDlgBase */
class AboutDlg : public AboutDlgBase
{
	wxBitmap m_bmp;
public:
	/** Constructor */
	AboutDlg( wxWindow* parent, const wxString &mainTitle );
	virtual ~AboutDlg();
	void SetInfo(const wxString &info);
	wxString GetInfo() const;
};

#endif // _ABOUTDLG_H_
