#ifndef __compilerassembleroptionspage__
#define __compilerassembleroptionspage__

/**
@file
Subclass of CompilerAssemblerOptionsBase, which is generated by wxFormBuilder.
*/

#include "compiler_pages.h"
#include "compiler.h"
#include "advanced_settings.h"

/** Implementing CompilerAssemblerOptionsBase */
class CompilerAssemblerOptionsPage : public CompilerAssemblerOptionsBase, public ICompilerSubPage
{
	wxString m_cmpname;
	long m_selectedCmpOption;
public:
	/** Constructor */
	CompilerAssemblerOptionsPage( wxWindow* parent, const wxString &cmpname );
	virtual void Save(CompilerPtr cmp);

protected:
	// Virtual event handlers from wxFormBuilder base class
	virtual void OnAssemblerOptionActivated( wxListEvent& event );
	virtual void OnAssemblerOptionDeSelected( wxListEvent& event );
	virtual void OnAssemblerOptionSelected( wxListEvent& event );
	virtual void OnNewAssemblerOption( wxCommandEvent& event );
	virtual void OnDeleteAssemblerOption( wxCommandEvent& event );
};

/** Implementing AssemblerOptionDlgBase */
class AssemblerOptionDialog : public AssemblerOptionDlgBase
{
public:
	AssemblerOptionDialog(wxWindow* parent, const wxString& title, const wxString& name, const wxString& help, wxWindowID id = wxID_ANY)
	: AssemblerOptionDlgBase(parent, id, title)
	{
		m_sName = name;
		m_sHelp = help;
	}
};

class CompilerAssemblerOptionDialog : public AssemblerOptionDialog
{
public:
	CompilerAssemblerOptionDialog(wxWindow* parent, const wxString& name, const wxString& help)
	: AssemblerOptionDialog(parent, wxT("Compiler option"), name, help)
	{
	}
};

#endif // __compilerassembleroptionspage__
