Document: embeddedlite
Title: Debian embeddedlite Manual
Author: <insert document author here>
Abstract: This manual describes what embeddedlite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/embeddedlite/embeddedlite.sgml.gz

Format: postscript
Files: /usr/share/doc/embeddedlite/embeddedlite.ps.gz

Format: text
Files: /usr/share/doc/embeddedlite/embeddedlite.text.gz

Format: HTML
Index: /usr/share/doc/embeddedlite/html/index.html
Files: /usr/share/doc/embeddedlite/html/*.html
