/**
  \file 

  \brief EmbeddedLite file
  \author V. Ridtchenko

  \notes

  Copyright: (C) 2010 by Victor Ridtchenko

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
*/
#ifndef __formbuildsettingsdlg__
#define __formbuildsettingsdlg__

/**
@file
Subclass of FormBuildSettingsBaseDlg, which is generated by wxFormBuilder.
*/

#include "formbuildsettingsbasedlg.h"
class IManager;

/** Implementing FormBuildSettingsBaseDlg */
class FormBuildSettingsDlg : public FormBuildSettingsBaseDlg
{
	IManager *m_mgr;
	
protected:
	// Handlers for FormBuildSettingsBaseDlg events.
	void OnButtonBrowse( wxCommandEvent& event );
	void OnButtonOK( wxCommandEvent& event );
	void OnButtonCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	FormBuildSettingsDlg( wxWindow* parent, IManager *mgr );
};

#endif // __formbuildsettingsdlg__
